### ISSUE TITLE
Determine how to avoid infinite loops when broadcasting messages to channel

### ISSUE THREAD

**Issue by vfunshteyn-zw** [wreedzw/int-zipchat#1]
We have a few options here:

- find a way to go around SaaS, and post directly to CMG
- allow republishing to the Kafka topic via int-data, and filter out incoming messages to exclude those with source address being the channel number, unless it's also coming from member with superuser id.
- harness existing deduplication int module.

**Comment by wreedzw** [comment]
I believe we can filter out messages from the source address which are also prepended with a member name.

**Comment by vfunshteyn-zw** [comment]
The direct to CMG option appears viable as well, since we should be able to inject messages from our demo environment (local box) into CMG Kafka topic or JMS queue - those should be exposed on the VPN. This should be doable with no auth or any kind of session key, the code that does this is here: https://github.com/Zipwhip/cloud-messaging-gateway/blob/development/src/main/java/com/zipwhip/cloud/messaging/gateway/send/message/SendMessageRequestFlowConfiguration.java

As for the message payload format, it looks like a simple Java Map is expected, with text Base64-encoded: https://github.com/Zipwhip/cloud-messaging-gateway/blob/development/src/main/java/com/zipwhip/cloud/messaging/gateway/send/message/SendMessageRequestTransformer.java

**Comment by wreedzw** [comment]
Closing as this is working correctly.
